<a href="https://colab.research.google.com/github/kellianneyang/bootcamp-assignments/blob/main/Bakery_NumPy_Exercise_(Core).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Bakery NumPy Exercise (Core)

Name: Kellianne Yang

In [ ]:
import numpy as np

In [ ]:
# Teens for Tech
# brownie: $2
# cookie: $1
# cake: $10
# goal: $200

In [ ]:
names_list = ["brownie", "cookie", "cake"]
print(names_list)

['brownie', 'cookie', 'cake']


In [ ]:
prices_list = [2, 1, 10]
print(prices_list)

[2, 1, 10]


In [ ]:
quantities_sold_list = [17, 40, 1]
print(quantities_sold_list)

[17, 40, 1]


In [ ]:
# prices_list * quantities_sold_list
# throws a type error

In [ ]:
names = np.array(names_list)
prices = np.array(prices_list)
quantities_sold = np.array(quantities_sold_list)

print(names, prices, quantities_sold)

['brownie' 'cookie' 'cake'] [ 2  1 10] [17 40  1]


In [ ]:
# arrays are ordered and mutable (like lists), but they are faster and more 
# memory-efficient

In [ ]:
# element-wise calculation: first element in each array is calculated, then 
# second element in each array, etc.
gross_profit = prices * quantities_sold
display(gross_profit)

array([34, 40, 10])

In [ ]:
expenses_list = [0.25, 0.50, 5]
expenses = np.array(expenses_list)
display(expenses)

array([0.25, 0.5 , 5.  ])

In [ ]:
net_profit_per_good = prices - expenses
display(net_profit_per_good)

array([1.75, 0.5 , 5.  ])

In [ ]:
# element-wise booleans: a new array created based on the T/F value of a statement
net_profit_per_good > 2

array([False, False,  True])

In [ ]:
index_profits = net_profit_per_good > 2
display(index_profits)

array([False, False,  True])

In [ ]:
# if we want the names of the goods, we can slice the names array with the
# index_profits array
names[index_profits]

array(['cake'], dtype='<U7')

In [ ]:
# python assumes that we want a result with only the "True" elements
# if we want the opposite, we can use the operator ~ (NOT)
~index_profits

array([ True,  True, False])

In [ ]:
names[~index_profits]

array(['brownie', 'cookie'], dtype='<U7')

In [ ]:
# adding (= appending) a value to an array
prices = np.append(prices, 7)
display(prices)

array([ 2,  1, 10,  7])

In [ ]:
names = np.append(names, "pie")
display(names)

array(['brownie', 'cookie', 'cake', 'pie'], dtype='<U7')

In [ ]:
# adding (= appending) multiple values to an array at once: append a LIST
prices = np.append(prices, [4.5, 3, 4, 9])
display(prices)

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ,  9. ])

In [ ]:
names = np.append(names, ["fudge", "cupcake", "banana bread", "torte"])
display(names)

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread', 'torte'], dtype='<U12')

In [ ]:
# deleting an element from an np array(identify element by index)
names = np.delete(names, -1)
prices = np.delete(prices, -1)
display(names)
display(prices)

array(['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
       'banana bread'], dtype='<U12')

array([ 2. ,  1. , 10. ,  7. ,  4.5,  3. ,  4. ])

In [ ]:
# getting the indices of elements in an np array: enumerate()
# need to loop through the array
# enumerate returns index, value

for i, name in enumerate(names):
  print(f"Index {i}: {name}")

Index 0: brownie
Index 1: cookie
Index 2: cake
Index 3: pie
Index 4: fudge
Index 5: cupcake
Index 6: banana bread


In [ ]:
# more on enumerate:
# we can put more than two variables in the enumerate call (indirectly), 
# if we have another corresponding array, as follows:

for i, name in enumerate(names):
  print(f"Index {i}: {name} (price = ${prices[i]})")

Index 0: brownie (price = $2.0)
Index 1: cookie (price = $1.0)
Index 2: cake (price = $10.0)
Index 3: pie (price = $7.0)
Index 4: fudge (price = $4.5)
Index 5: cupcake (price = $3.0)
Index 6: banana bread (price = $4.0)


In [ ]:
# replacing an element in an np array (identify element by index)
# in this example we just want to replace the price of cakes, so the names
# array is unchanged but we need to change the prices array

prices[2] = 12
print(names[2])
print(prices[2])

cake
12.0


In [ ]:
# INTRO TO PANDAS

In [ ]:
import pandas as pd

In [ ]:
# series are used for 1d data
# dataframes are used for 2d data

In [ ]:
# the only required argument for a series is as array, and it will
# look like this:
prices_pd = pd.Series(prices)
display(prices_pd)

0     2.0
1     1.0
2    12.0
3     7.0
4     4.5
5     3.0
6     4.0
dtype: float64

In [ ]:
# you can pass another array for pandas to use as the index for the series
# (default is to have an integer array as above)
prices_pd = pd.Series(prices, index=names)
display(prices_pd)

brownie          2.0
cookie           1.0
cake            12.0
pie              7.0
fudge            4.5
cupcake          3.0
banana bread     4.0
dtype: float64

In [ ]:
# slicing from a series: need to use .loc[], with the index in []
prices_pd.loc["cake"]

12.0

In [ ]:
# to access the numpy array of values from the series without the indices:
# use the .values attribute
display(prices_pd.values)

array([ 2. ,  1. , 12. ,  7. ,  4.5,  3. ,  4. ])

In [ ]:
# 2-DIMENSIONAL NUMPY ARRAYS
# make sure that all lists are the same length
data = np.array([names_list, prices_list, expenses_list, quantities_sold])
display(data)

array([['brownie', 'cookie', 'cake'],
       ['2', '1', '10'],
       ['0.25', '0.5', '5'],
       ['17', '40', '1']], dtype='<U32')

In [ ]:
print(data.shape)

(4, 3)


In [ ]:
print(data.ndim)

2


In [ ]:
# can combine arrays using np.stack
# throws an error
# np.stack([names, prices, expenses, quantities_sold])

In [ ]:
print(names.shape, prices.shape, expenses.shape, quantities_sold.shape)

(7,) (7,) (3,) (3,)


In [ ]:
expenses = np.append(expenses, [3.5, 2, .9, 1.25])
quantities_sold = np.append(quantities_sold, [0, 0, 0, 0])
display(expenses, quantities_sold)

array([0.25, 0.5 , 5.  , 3.5 , 2.  , 0.9 , 1.25])

array([17, 40,  1,  0,  0,  0,  0])

In [ ]:
data = np.stack([names, prices, expenses, quantities_sold])
print(data.shape)
display(data)

(4, 7)


array([['brownie', 'cookie', 'cake', 'pie', 'fudge', 'cupcake',
        'banana bread'],
       ['2.0', '1.0', '12.0', '7.0', '4.5', '3.0', '4.0'],
       ['0.25', '0.5', '5.0', '3.5', '2.0', '0.9', '1.25'],
       ['17', '40', '1', '0', '0', '0', '0']], dtype='<U32')

In [ ]:
# to access a single datum in a 2D array, think of it as a spreadsheet
# you need two numbers: first for the first axis location, and second for the second axis location
# first number locates the row, second number locates the column

# if you give a 2D array a single value to access, it will give you the 1D array at that location
# arrays are zero-indexed

data[1]

array(['2.0', '1.0', '12.0', '7.0', '4.5', '3.0', '4.0'], dtype='<U32')

In [ ]:
# one way to access: two sets of square brackets, one after another
data[1][1]

'1.0'

In [ ]:
# another way to access: one set of square brackets with a comma inside
data[1, 1]

'1.0'

In [ ]:
# Pandas DataFrame allows us to label our arrays
# first axis (rows) is referred to as index
# second axis (columns) is referred to as columns

# index and columns are arguments you can give pd.DataFrame

# create a pd.DataFrame from an np.array

baking_df = pd.DataFrame(data, index = ['names', 'price', 'expenses', 'quantities_sold'])
display(baking_df)

0       1     2    3      4        5             6
names            brownie  cookie  cake  pie  fudge  cupcake  banana bread
price                2.0     1.0  12.0  7.0    4.5      3.0           4.0
expenses            0.25     0.5   5.0  3.5    2.0      0.9          1.25
quantities_sold       17      40     1    0      0        0             0

In [ ]:
# switch the rows and columns by using transpose: df.T

baking_df = baking_df.T
display(baking_df)

names price expenses quantities_sold
0       brownie   2.0     0.25              17
1        cookie   1.0      0.5              40
2          cake  12.0      5.0               1
3           pie   7.0      3.5               0
4         fudge   4.5      2.0               0
5       cupcake   3.0      0.9               0
6  banana bread   4.0     1.25               0

In [ ]:
baking_df = baking_df.set_index('names')
display(baking_df)

price expenses quantities_sold
names                                      
brownie        2.0     0.25              17
cookie         1.0      0.5              40
cake          12.0      5.0               1
pie            7.0      3.5               0
fudge          4.5      2.0               0
cupcake        3.0      0.9               0
banana bread   4.0     1.25               0

In [ ]:
# Bakery NumPy Exercise (Core)
# step 1
# Open the notebook you created during the previous lesson: "Working With NumPy 
# Arrays"

# step 2
# Use enumerate to loop through the names array and print the index number and 
# name for every baked good.

for i in enumerate(names):
  print(f"Index {i}")

print('')

for i, name in enumerate(names):
  print(f"Index {i}: {name}")


Index (0, 'brownie')
Index (1, 'cookie')
Index (2, 'cake')
Index (3, 'pie')
Index (4, 'fudge')
Index (5, 'cupcake')
Index (6, 'banana bread')

Index 0: brownie
Index 1: cookie
Index 2: cake
Index 3: pie
Index 4: fudge
Index 5: cupcake
Index 6: banana bread


In [ ]:
# step 3
# Update the quantity_sold_array to include the sale of 2 pies, 3 trays of 
# fudge, 16 cupcakes, and 5 loaves of banana bread. You also realize that one 
# of the cookies you thought was sold had actually fallen on the ground, so 
# edit the quantity_sold_array from 40 to 39.

quantities_sold[3] = 2
quantities_sold[4] = 3
quantities_sold[5] = 16
quantities_sold[6] = 5
quantities_sold[1] = 39

display(quantities_sold)

array([17, 39,  1,  2,  3, 16,  5])

In [ ]:
# step 4
# Determine the amount of money collected from the sale of each item at the 
# bake sale.

gross_profits = quantities_sold * prices
print(f"Gross profits: {gross_profits}")

Gross profits: [34.  39.  12.  14.  13.5 48.  20. ]


In [ ]:
# step 5
# Create a NumPy array "quantity_leftover" that includes the quantity of each 
# item remaining at the end of the sale: 2 cakes, 1 pie, 6 trays of fudge, 2 
# loaves of banana bread. Hint: Make sure to include "0" for any item that was 
# sold out. Why is this important when creating the array?
# A: the arrays need to be the same shapes to do any calculations

quantity_leftover = np.array([0, 0, 2, 1, 6, 0, 2])
display(quantity_leftover)

array([0, 0, 2, 1, 6, 0, 2])

In [ ]:
# step 6
# The club decides to sell the leftover items at half price and everything 
# quickly sells out! Determine how much money was collected from the clearance 
# sale.

clearance_sale_gross_profits = quantity_leftover * (prices * 0.5)
print(f"Clearance Sale gross profits: {clearance_sale_gross_profits}")

clearance_sale_sum = clearance_sale_gross_profits.sum()
print(f"Clearance Sale sum: {clearance_sale_sum}")

Clearance Sale gross profits: [ 0.   0.  12.   3.5 13.5  0.   4. ]
Clearance Sale sum: 33.0


In [ ]:
# step 7
# How much total money was collected from the bake sale (including the sale of 
# full price and clearance items)?

total_gross_profits = gross_profits + clearance_sale_gross_profits
total_money = total_gross_profits.sum()
print(f"Total money generated: ${total_money:.2f}")

Total money generated: $213.50
